In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataFrame = pd.read_csv("data\champ_mutation_list_q4.csv")

In [3]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3756 entries, 0 to 3755
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   HGVS cDNA                      3756 non-null   object
 1   hg19 Coordinates               3734 non-null   object
 2   HGVS Protein                   3199 non-null   object
 3   Mature Protein                 3207 non-null   object
 4   Mutation Type                  3756 non-null   object
 5   Mechanism                      3736 non-null   object
 6   Exon                           3756 non-null   object
 7   Codon                          3510 non-null   object
 8   Domain                         3223 non-null   object
 9   Subtype                        3414 non-null   object
 10  In Poly A                      3756 non-null   object
 11  Severe (<1 U/dL)               1858 non-null   object
 12  Moderate (1-5 U/dL)            587 non-null    object
 13  Mild (>5 U/dL)                 703 non-null    object
 14  Unclassified (no FVIII level)  784 non-null    object
 15  Reported Severity              3756 non-null   object
 16  History of Inhibitor           3756 non-null   object
 17  Comments                       120 non-null    object
 18  Reference ID                   3756 non-null   object
 19  Year Reported                  3756 non-null   object
dtypes: object(20)
memory usage: 587.0+ KB

In [4]:
dataFrame.shape

(3756, 20)

In [5]:
dataFrame.isnull().sum()

HGVS cDNA                           0
hg19 Coordinates                   22
HGVS Protein                      557
Mature Protein                    549
Mutation Type                       0
Mechanism                          20
Exon                                0
Codon                             246
Domain                            533
Subtype                           342
In Poly A                           0
Severe (<1 U/dL)                 1898
Moderate (1-5 U/dL)              3169
Mild (>5 U/dL)                   3053
Unclassified (no FVIII level)    2972
Reported Severity                   0
History of Inhibitor                0
Comments                         3636
Reference ID                        0
Year Reported                       0
dtype: int64

In [6]:
dataFrame.dtypes

HGVS cDNA                        object
hg19 Coordinates                 object
HGVS Protein                     object
Mature Protein                   object
Mutation Type                    object
Mechanism                        object
Exon                             object
Codon                            object
Domain                           object
Subtype                          object
In Poly A                        object
Severe (<1 U/dL)                 object
Moderate (1-5 U/dL)              object
Mild (>5 U/dL)                   object
Unclassified (no FVIII level)    object
Reported Severity                object
History of Inhibitor             object
Comments                         object
Reference ID                     object
Year Reported                    object
dtype: object

In [7]:
dataFrame.nunique()

HGVS cDNA                        3735
hg19 Coordinates                 2873
HGVS Protein                     3016
Mature Protein                   3020
Mutation Type                      10
Mechanism                          12
Exon                              184
Codon                            1705
Domain                             13
Subtype                             7
In Poly A                           2
Severe (<1 U/dL)                    1
Moderate (1-5 U/dL)                 1
Mild (>5 U/dL)                      2
Unclassified (no FVIII level)       5
Reported Severity                  14
History of Inhibitor                6
Comments                           28
Reference ID                      399
Year Reported                      36
dtype: int64

In [8]:
dataFrame['Year Reported'] = pd.to_numeric(dataFrame['Year Reported'], errors='coerce', downcast='integer').astype('Int64')

In [9]:
dataFrame['hg19 Coordinates'] = pd.to_numeric(dataFrame['hg19 Coordinates'], errors='coerce', downcast='integer').astype('Int64')

In [10]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3756 entries, 0 to 3755
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   HGVS cDNA                      3756 non-null   object
 1   hg19 Coordinates               3024 non-null   Int64
 2   HGVS Protein                   3199 non-null   object
 3   Mature Protein                 3207 non-null   object
 4   Mutation Type                  3756 non-null   object
 5   Mechanism                      3736 non-null   object
 6   Exon                           3756 non-null   object
 7   Codon                          3510 non-null   object
 8   Domain                         3223 non-null   object
 9   Subtype                        3414 non-null   object
 10  In Poly A                      3756 non-null   object
 11  Severe (<1 U/dL)               1858 non-null   object
 12  Moderate (1-5 U/dL)            587 non-null    object
 13  Mild (>5 U/dL)                 703 non-null    object
 14  Unclassified (no FVIII level)  784 non-null    object
 15  Reported Severity              3756 non-null   object
 16  History of Inhibitor           3756 non-null   object
 17  Comments                       120 non-null    object
 18  Reference ID                   3756 non-null   object
 19  Year Reported                  3558 non-null   Int64
dtypes: Int64(2), object(18)
memory usage: 594.3+ KB

In [11]:
dataFrame

,HGVS cDNA,hg19 Coordinates,HGVS Protein,Mature Protein,Mutation Type,Mechanism,Exon,Codon,Domain,Subtype,In Poly A,Severe (<1 U/dL),Moderate (1-5 U/dL),Mild (>5 U/dL),Unclassified (no FVIII level),Reported Severity,History of Inhibitor,Comments,Reference ID,Year Reported
0,c.*1001C>T,154064871,NaN,NaN,3'UTR,Substitution,3'UTR,NaN,3'UTR,NaN,N,NaN,NaN,NaN,X,Not reported,Not reported,NaN,290,2017
1,c.*1009A>C,154064863,NaN,NaN,3'UTR,Substitution,3'UTR,NaN,3'UTR,NaN,N,NaN,NaN,NaN,X,Not reported,Not reported,NaN,290,2017
2,c.*1060C>T,154064812,NaN,NaN,3'UTR,Substitution,3'UTR,NaN,3'UTR,NaN,N,NaN,NaN,NaN,X,Not reported,Not reported,NaN,290,2017
3,c.*108A>G,154065764,NaN,NaN,3'UTR,Substitution,3'UTR,NaN,3'UTR,NaN,N,NaN,NaN,NaN,X,Not reported,Not reported,NaN,290,2017
4,c.*1513A>G,154064359,NaN,NaN,3'UTR,Substitution,3'UTR,NaN,3'UTR,NaN,N,NaN,NaN,NaN,X,Not reported,Not reported,NaN,290,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3751,Not reported,<NA>,p.Ile2100Thrfs*42,Ile2081Thrfs*42,Frameshift,NaN,22,2081,C1,Light chain,N,X,NaN,NaN,NaN,Severe,Not reported,NaN,297,2018
3752,Not reported,<NA>,p.Asn2236*,Asn2217*,Nonsense,NaN,24,2217,C2,Light chain,N,X,NaN,NaN,NaN,Severe,Not reported,NaN,297,2018
3753,Not reported,<NA>,p.Gln2265*,Gln2246*,Nonsense,NaN,25,2246,C2,Light chain,N,X,NaN,NaN,NaN,Severe,Not reported,NaN,297,2018
3754,Not reported,<NA>,p.Met2274Asnfs*79+32,Met2255Asnfs*79+32,Frameshift,NaN,25,2255,C2,Light Chain,N,X,NaN,NaN,NaN,Severe,Not reported,NaN,297,2018
3755,Not reported,<NA>,p.Arg52*,Arg33*,Nonsense,NaN,2,33,A1,Heavy chain,N,X,NaN,NaN,NaN,Severe,Not reported,NaN,297,2018